---
lang_id: 2

messages:

errors:
  # Ошибки создаваемые AppError

  errUnexpectedInternal: # 418
    reason: "Internal server error [problem]"
    details:
      - "unexpected error"

  errInternal: # 500
    reason: "Internal server error"

  errSystem: # 503
    reason: "System server error"

  errHttpClientUnauthorized: # 401
    reason: "User authorization required"

  errHttpAccessForbidden: # 403
    reason: "Forbidden - You don't have permission to access"

  errHttpResourceNotFound: # 404
    reason: "Resource Not Found"

  errHttpRequestParseData: # 422
    reason: "Request body is not valid: '{{ .reason }}'"
    details:
      - "проверьте параметры запроса, правильность формата json и соответствующих ему типов"

  errUseCaseTemporarilyUnavailable: # 503
    reason: "The system is temporarily unable to process your request. Please try again later"

  # Ошибки генерируемые валидатором (400).
  # ID формируется из "validator_err" и имени валидатора, которое указано
  # в `` поля структуры (например: min, max, required).
  # Можно использовать следующие переменные:
  #   {{ .name }} - название поля, где произошла ошибка;
  #   {{ .type }} - тип поля (например: int32);
  #   {{ .value }} - текущее значение поля;
  #   {{ .param }} - параметр валидатора (например: max=16 -> param=16);

  validator.err_required:
    reason: "The field is required"

  validator.err_min:
    reason: "The field value must be at least {{ .param }} characters (current value: {{ .value }})"

  validator.err_max:
    reason: "The field value must be no more than {{ .param }} characters"

  validator.err_gte:
    reason: "The field value must be greater than or equal to {{ .param }} (current value: {{ .value }})"

  validator.err_lte:
    reason: "The field value must be less than or equal to {{ .param }} (current value: {{ .value }})"

  validator.err_http_url:
    reason: "The field value must be URL address (current value: {{ .value }})"